@startuml


IDLE:
PRODUCING:
BLOCKING:
UNREADY:
READY:


[*] --> IDLE

IDLE --> PRODUCING : produce

PRODUCING --> READY : onContent
BLOCKING --> READY : onContent
UNREADY --> READY : onContent
IDLE --> READY : onContent

BLOCKING -up-> IDLE : onWakeup
UNREADY -left-> IDLE : onWakeup


PRODUCING -left-> IDLE : POLL
PRODUCING --> BLOCKING : BLOCK
PRODUCING -left-> UNREADY : ASYNC

READY -up-> IDLE : return content
@enduml