@startuml

IDLE:
PRODUCING:
BLOCKING:
CONTENT:
UNREADY:
PRODUCABLE:
READY:
EOF:

[*] --> IDLE

IDLE --> CONTENT : onContent
IDLE --> PRODUCING : produce

PRODUCING --> CONTENT : onContent
PRODUCING -right-> IDLE : POLL
PRODUCING --> BLOCKING : BLOCK
PRODUCING --> UNREADY : ASYNC

CONTENT -left-> IDLE : return content
CONTENT --> EOF : return EOF or Error

BLOCKING --> CONTENT : onContent
BLOCKING -up-> IDLE : onContentProducable

UNREADY --> READY : onContent
UNREADY -up-> PRODUCABLE : onContentProducable

PRODUCABLE -left->IDLE : nextAction

READY -up-> IDLE : return content
READY --> EOF : return EOF or Error

@enduml